# Generated by Django 4.0.5 on 2022-06-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jsonfile',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Login', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
