# Generated by Django 3.2.10 on 2022-06-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JsonFile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jsonfile',
            new_name='JsonfileModel',
        ),
    ]
