# Generated by Django 3.2.10 on 2022-06-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JsonFile', '0003_auto_20220617_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Name',
        ),
    ]
